name: Build and Distribute App

on:
  push:
    branches:
      - '**' # Triggers on push to any branch

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Calculate Version
        id: version
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          # The prefix to use to create tags
          tag_prefix: "v"
          # A string which, if present in a git commit, indicates that a change represents a
          # major (breaking) change, supports regular expressions wrapped with /
          major_pattern: "(MAJOR)"
          # A string which, if present in a git commit, indicates that a change represents a
          # minor (feature) change, supports regular expressions wrapped with /
          minor_pattern: "(MINOR)|feat:"
          # Pattern to determine which commits to include in version calculation
          version_format: "${major}.${minor}.${patch}"
          # If true, every commit will be treated as a patch bump if no other pattern matches
          bump_each_commit: true

      - name: Build Debug APK
        # Usamos github.run_number como versionCode para garantizar un entero incremental Ãºnico.
        run: ./gradlew app:assembleDebug -PversionCode=${{ github.run_number }} -PversionName=${{ steps.version.outputs.version }} --parallel --build-cache

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
          releaseNotes: ${{ github.event.head_commit.message }}
